#!/usr/bin/perl

#
# Copyright (C) 2013 Nethesis S.r.l.
# http://www.nethesis.it - support@nethesis.it
# 
# This script is part of NethServer.
# 
# NethServer is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License,
# or any later version.
# 
# NethServer is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with NethServer.  If not, see <http://www.gnu.org/licenses/>.
#

use strict;
use esmith::Build::CreateLinks qw(:all);

#
# nethserver-flashstart-update event
#

my $event = 'nethserver-flashstart-update';

event_actions($event, qw(
      initialize-default-databases 00
      nethserver-flashstart-conf 20
));

event_templates($event, qw(
                 /etc/squid/squid.conf
));

event_services($event, 'squid' => 'restart');

#
# nethserver-flashstart-save event
#

$event = 'nethserver-flashstart-save';

event_actions($event, qw(
      initialize-default-databases 00
));

event_templates($event, qw(
                 /etc/squid/squid.conf
));


event_services($event, 'squid' => 'reload');
