#!/usr/bin/php
<?php

class FlashStartWS
{
    /**
     * Reseller's user name for FlashStart web site
     *
     * @var string
     */
    private $user = '';

    /**
     * Reseller's password for FlashStart web site
     *
     * @var string
     */
    private $password = '';

    /**
     * WISDL url for FlashStart
     *
     * @var string
     */
    private $url = 'http://cloud.flashstart.it/ServiceFS/FlashStart.Service.php?wsdl';

    /**
     * SOAP client
     *
     * @var object
     */
    private $client = NULL;

    /**
     * FlashStart token
     *
     * @var object
     */
    private $token = NULL;


    /**
     * Create a SOAP client for FlashStart web site
     *
     * @param string $user reseller's user name
     * @param string $password reseller's password
     * @param string $url WISDL url (optional)
     *
     * @api
     * @return FlashStart
     */
    public function __construct($user, $password, $url = '')
    {
        $this->user = $user;
        $this->password = $password;
        if ($url) {
            $this->url = $url;
        }
        $this->client = new SoapClient($this->url);
        try {
            $this->token = $this->client->Login(array('UserName' => $this->user, 'Password' => $this->password, 'ApplicationID' => 'WBS'));
            if ($this->token->TokenID == "null") {
                throw new Exception('Bad credentials');
            }
        } catch (Exception $e) {
            $this->handleException($e);
        }
    }

    private function handleException(Exception $ex)
    {
        echo "FlashStartWS error: " . $ex->getMessage(). "\n";
        exit(1);
    }

    public function getReport()
    {
        $ret = array();
        try {
            $result = $this->client->InfoSedeProfile(array('UserAdmin' => $this->user, 'TokenID' => $this->token->TokenID, 'TransactionID' => 'GET_REPORT'));

            ## TODO
            return $ret;
        } catch (\Exception $e) {
            $this->handleException($e);
        }
    }
}

$flash = json_decode(exec("/sbin/e-smith/config getjson flashstart"));
print_r($flash);
$ws = new FlashStartWS($flash->props->Username,$flash->props->Password);
$ws->getReport();
