#!/usr/bin/perl

use Net::DNS;
use List::Util qw/shuffle/;
use constant DEBUG => 0;

my $port = $ARGV[0] || "53";
our $LOG;

$SIG{INT}  = \&signal_handler;
$SIG{TERM} = \&signal_handler;

sub signal_handler {
    close $LOG unless (DEBUG == 0);
    exit 0;
}

$|=1;
if (DEBUG == 1) {
    open ($LOG, '>>', '/var/log/squid/flashstart-acl.log');
    $LOG->autoflush;
}
while (<STDIN>) {
    $_ =~ s/^\s+//;
    $_ =~ s/\s+$//;
    print valid($_, $port);
    print "\n";
}
close $LOG;
exit 0;

sub valid {
    my $host = shift;
    my $port = shift || '53';
    my @servers = shuffle ('188.94.192.215','85.18.248.198');
 
    my $res = Net::DNS::Resolver->new(
        nameservers => [@servers],
  	recurse     => 1,
  	debug       => 0,
        port        => $port
   );
   
   print $LOG $host unless (DEBUG == 0);
   my $q = $res->search($host);
   if ($q) {
       foreach $rr ($q->answer) {
           next unless $rr->type eq "A";
           print $LOG " -> ".$rr->address unless (DEBUG == 0);
           if ( $rr->address ~~ @servers )  {
               print $LOG " -> ERR\n" unless (DEBUG == 0);
               return "ERR";
           } else {
               print $LOG " -> OK\n" unless (DEBUG == 0);
               return "OK";
           }
       }
   } else {
       print $LOG " -> ERR message=no answer\n" unless (DEBUG == 0);
       return "ERR message=no answer";
   }
}
