#!/usr/bin/perl

use Net::DNS;
use List::Util qw/shuffle/;

my $port = $ARGV[0] || "53";
my $whitelist = 'flashstart.it';

$SIG{INT}  = \&signal_handler;
$SIG{TERM} = \&signal_handler;

sub signal_handler {
    exit 0;
}

$|=1;
while (<STDIN>) {
    $_ =~ s/^\s+//;
    $_ =~ s/\s+$//;
    if ($_ =~ /$whitelist/) {
        print "OK message=whitelisted";
    } else {
        print valid($_, $port);
    }
    print "\n";
}
exit 0;

sub valid {
    my $host = shift;
    my $port = shift || '53';
    my @servers = shuffle ('188.94.192.215','85.18.248.198');
 
    my $res = Net::DNS::Resolver->new(
        nameservers => [@servers],
  	recurse     => 1,
  	debug       => 0,
        port        => $port
   );
   
   my $q = $res->search($host);
   if ($q) {
       foreach $rr ($q->answer) {
           next unless $rr->type eq "A";
           if ( $rr->address ~~ @servers )  {
               return "ERR";
           } else {
               return "OK";
           }
       }
   } else {
       return "ERR message=no answer";
   }
}
