#!/usr/bin/php
<?php
$user = '';
$password = '';

$system_id = json_decode(exec("/sbin/e-smith/db configuration getjson nethupdate SystemID"));
$user = $system_id->props->SystemID;
if (!$user) {
    echo "No SystemID found";
    exit(1);
}

$network_db = json_decode(exec("/sbin/e-smith/db networks printjson"));
$bridge = false;
foreach ($network_db as $key) {
    if ($key->props->role == 'green') {
        if ($key->type == 'bridge') {
            $bridge = $key->props->device;
        } else {
            $password = $key->props->hwaddr;
            break;
        }
    }
    // search for ethernet associated with the bridge 
    if ($bridge) {
        if ($key->props->role == 'bridged' && $key->props->bridge == $bridge) {
            $password = $key->props->hwaddr;
            break;
        }
    }
}
if (!$password) {
    echo "No suitable MAC found";
    exit(1);
}
   
$hostname = json_decode(exec("/sbin/e-smith/db configuration getjson SystemName"));
$hostname = $hostname->type;
$domainname = json_decode(exec("/sbin/e-smith/db configuration getjson DomainName"));
$domainname = $domainname->type;
$fqdn="$hostname.$domainname";


$url = "http://$user:$password@188.94.192.215/nic/update";
$query = "hostname=$fqdn&wildcard=NOCHG&mx=NOCHG&backmx=NOCHG";

$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $url);
curl_setopt($ch, CURLOPT_POST, 0);
curl_setopt($ch, CURLOPT_POSTFIELDS,$query);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_FOLLOWLOCATION, true);
$return = trim(curl_exec ($ch));
curl_close ($ch);

if($return == 'good') {
   exit(0);
}  else {
   exit(1);
}

